### PR TITLE
Build Executables using GitHub Actions

### PR DESCRIPTION
**Pull request by naveen521kk**
This is for ease of users to download and install the build artificial rather then building themselves ( they may not have build tools).

### CODE REVIEW

**Comment by eulertour** [comment]
According to the documentation [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder) and [here](https://www.electron.build/configuration/win) you can build to msi on windows by adding editing `vue.config.js` to include
```
electronBuilder: {
    ...
    "win": {
        "target": ["msi"]
    }
}
```
or you can stick with exe if you don't have the time to test it.

**Comment by eulertour** [comment]
Looking into this some more it actually seems like a portable app would be better for windows, since it doesn't have to be installed.

**Comment by naveen521kk** [comment]
> or you can stick with exe if you don't have the time to test it.

Sticking to exe looks good for me now,

**Comment by naveen521kk** [comment]
@eulertour did you revert this PR?

**Pull request merged**
